# Generated by Django 6.0.5 on 2026-05-25 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nyondo', '0004_stock_remove_sale_category_remove_sale_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('nin_number', models.CharField(max_length=14, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('occupation', models.CharField(default='Salary Earner', max_length=100)),
                ('employer_name', models.CharField(blank=True, max_length=150)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeGoodsPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_taken', models.PositiveIntegerField()),
                ('pickup_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.schemecustomer')),
                ('linked_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nyondo.sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo.stock')),
            ],
        ),
        migrations.CreateModel(
            name='SchemePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.schemecustomer')),
            ],
        ),
    ]
